spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mob7
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
      
server:
  servlet:
    context-path: /api


# custom path for swagger-ui
springdoc:
  version: 1.0.0
  swagger-ui:
    path: /swagger-ui-custom.html
# custom path for api docs
  api-docs:
    path: /api-docs

logging:
  level:
    web: DEBUG